USE propagation;
DROP TABLE IF EXISTS header_tbl;
DROP TABLE IF EXISTS detail_tbl;

CREATE TABLE IF NOT EXISTS header_tbl(
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT , 
 name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS detail_tbl(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
header_id INT NOT NULL,
FOREIGN KEY (header_id) REFERENCES header_tbl(id)
);